// Code generated by go-swagger; DO NOT EDIT.

package transfer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGETReceiveInfoParams creates a new GETReceiveInfoParams object
// with the default values initialized.
func NewGETReceiveInfoParams() *GETReceiveInfoParams {
	var ()
	return &GETReceiveInfoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGETReceiveInfoParamsWithTimeout creates a new GETReceiveInfoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGETReceiveInfoParamsWithTimeout(timeout time.Duration) *GETReceiveInfoParams {
	var ()
	return &GETReceiveInfoParams{

		timeout: timeout,
	}
}

// NewGETReceiveInfoParamsWithContext creates a new GETReceiveInfoParams object
// with the default values initialized, and the ability to set a context for a request
func NewGETReceiveInfoParamsWithContext(ctx context.Context) *GETReceiveInfoParams {
	var ()
	return &GETReceiveInfoParams{

		Context: ctx,
	}
}

// NewGETReceiveInfoParamsWithHTTPClient creates a new GETReceiveInfoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGETReceiveInfoParamsWithHTTPClient(client *http.Client) *GETReceiveInfoParams {
	var ()
	return &GETReceiveInfoParams{
		HTTPClient: client,
	}
}

/*GETReceiveInfoParams contains all the parameters to send to the API endpoint
for the get receive info operation typically these are written to a http.Request
*/
type GETReceiveInfoParams struct {

	/*ID4N
	  The ID4N to retrieve information about

	*/
	ID4N string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get receive info params
func (o *GETReceiveInfoParams) WithTimeout(timeout time.Duration) *GETReceiveInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get receive info params
func (o *GETReceiveInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get receive info params
func (o *GETReceiveInfoParams) WithContext(ctx context.Context) *GETReceiveInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get receive info params
func (o *GETReceiveInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get receive info params
func (o *GETReceiveInfoParams) WithHTTPClient(client *http.Client) *GETReceiveInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get receive info params
func (o *GETReceiveInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID4N adds the id4n to the get receive info params
func (o *GETReceiveInfoParams) WithID4N(id4n string) *GETReceiveInfoParams {
	o.SetID4N(id4n)
	return o
}

// SetID4N adds the id4n to the get receive info params
func (o *GETReceiveInfoParams) SetID4N(id4n string) {
	o.ID4N = id4n
}

// WriteToRequest writes these params to a swagger request
func (o *GETReceiveInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id4n
	if err := r.SetPathParam("id4n", o.ID4N); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
