// Code generated by go-swagger; DO NOT EDIT.

package transfer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	api_models "github.com/BlueRainSoftware/id4i-cli/api_models"
)

// GETReceiveInfoReader is a Reader for the GETReceiveInfo structure.
type GETReceiveInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GETReceiveInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGETReceiveInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 202:
		result := NewGETReceiveInfoAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGETReceiveInfoUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGETReceiveInfoForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGETReceiveInfoNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 405:
		result := NewGETReceiveInfoMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 406:
		result := NewGETReceiveInfoNotAcceptable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 415:
		result := NewGETReceiveInfoUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGETReceiveInfoInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGETReceiveInfoOK creates a GETReceiveInfoOK with default headers values
func NewGETReceiveInfoOK() *GETReceiveInfoOK {
	return &GETReceiveInfoOK{}
}

/*GETReceiveInfoOK handles this case with default header values.

OK
*/
type GETReceiveInfoOK struct {
	Payload *api_models.TransferReceiveInfo
}

func (o *GETReceiveInfoOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/transfers/{id4n}/receiveInfo][%d] getReceiveInfoOK  %+v", 200, o.Payload)
}

func (o *GETReceiveInfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.TransferReceiveInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGETReceiveInfoAccepted creates a GETReceiveInfoAccepted with default headers values
func NewGETReceiveInfoAccepted() *GETReceiveInfoAccepted {
	return &GETReceiveInfoAccepted{}
}

/*GETReceiveInfoAccepted handles this case with default header values.

Accepted
*/
type GETReceiveInfoAccepted struct {
}

func (o *GETReceiveInfoAccepted) Error() string {
	return fmt.Sprintf("[GET /api/v1/transfers/{id4n}/receiveInfo][%d] getReceiveInfoAccepted ", 202)
}

func (o *GETReceiveInfoAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGETReceiveInfoUnauthorized creates a GETReceiveInfoUnauthorized with default headers values
func NewGETReceiveInfoUnauthorized() *GETReceiveInfoUnauthorized {
	return &GETReceiveInfoUnauthorized{}
}

/*GETReceiveInfoUnauthorized handles this case with default header values.

Unauthorized
*/
type GETReceiveInfoUnauthorized struct {
	Payload *api_models.APIError
}

func (o *GETReceiveInfoUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1/transfers/{id4n}/receiveInfo][%d] getReceiveInfoUnauthorized  %+v", 401, o.Payload)
}

func (o *GETReceiveInfoUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGETReceiveInfoForbidden creates a GETReceiveInfoForbidden with default headers values
func NewGETReceiveInfoForbidden() *GETReceiveInfoForbidden {
	return &GETReceiveInfoForbidden{}
}

/*GETReceiveInfoForbidden handles this case with default header values.

Forbidden
*/
type GETReceiveInfoForbidden struct {
	Payload *api_models.APIError
}

func (o *GETReceiveInfoForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/transfers/{id4n}/receiveInfo][%d] getReceiveInfoForbidden  %+v", 403, o.Payload)
}

func (o *GETReceiveInfoForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGETReceiveInfoNotFound creates a GETReceiveInfoNotFound with default headers values
func NewGETReceiveInfoNotFound() *GETReceiveInfoNotFound {
	return &GETReceiveInfoNotFound{}
}

/*GETReceiveInfoNotFound handles this case with default header values.

Not Found
*/
type GETReceiveInfoNotFound struct {
	Payload *api_models.APIError
}

func (o *GETReceiveInfoNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/transfers/{id4n}/receiveInfo][%d] getReceiveInfoNotFound  %+v", 404, o.Payload)
}

func (o *GETReceiveInfoNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGETReceiveInfoMethodNotAllowed creates a GETReceiveInfoMethodNotAllowed with default headers values
func NewGETReceiveInfoMethodNotAllowed() *GETReceiveInfoMethodNotAllowed {
	return &GETReceiveInfoMethodNotAllowed{}
}

/*GETReceiveInfoMethodNotAllowed handles this case with default header values.

Method not allowed
*/
type GETReceiveInfoMethodNotAllowed struct {
	Payload *api_models.APIError
}

func (o *GETReceiveInfoMethodNotAllowed) Error() string {
	return fmt.Sprintf("[GET /api/v1/transfers/{id4n}/receiveInfo][%d] getReceiveInfoMethodNotAllowed  %+v", 405, o.Payload)
}

func (o *GETReceiveInfoMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGETReceiveInfoNotAcceptable creates a GETReceiveInfoNotAcceptable with default headers values
func NewGETReceiveInfoNotAcceptable() *GETReceiveInfoNotAcceptable {
	return &GETReceiveInfoNotAcceptable{}
}

/*GETReceiveInfoNotAcceptable handles this case with default header values.

Not Acceptable
*/
type GETReceiveInfoNotAcceptable struct {
	Payload *api_models.APIError
}

func (o *GETReceiveInfoNotAcceptable) Error() string {
	return fmt.Sprintf("[GET /api/v1/transfers/{id4n}/receiveInfo][%d] getReceiveInfoNotAcceptable  %+v", 406, o.Payload)
}

func (o *GETReceiveInfoNotAcceptable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGETReceiveInfoUnsupportedMediaType creates a GETReceiveInfoUnsupportedMediaType with default headers values
func NewGETReceiveInfoUnsupportedMediaType() *GETReceiveInfoUnsupportedMediaType {
	return &GETReceiveInfoUnsupportedMediaType{}
}

/*GETReceiveInfoUnsupportedMediaType handles this case with default header values.

Unsupported Media Type
*/
type GETReceiveInfoUnsupportedMediaType struct {
	Payload *api_models.APIError
}

func (o *GETReceiveInfoUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[GET /api/v1/transfers/{id4n}/receiveInfo][%d] getReceiveInfoUnsupportedMediaType  %+v", 415, o.Payload)
}

func (o *GETReceiveInfoUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGETReceiveInfoInternalServerError creates a GETReceiveInfoInternalServerError with default headers values
func NewGETReceiveInfoInternalServerError() *GETReceiveInfoInternalServerError {
	return &GETReceiveInfoInternalServerError{}
}

/*GETReceiveInfoInternalServerError handles this case with default header values.

Internal Server Error
*/
type GETReceiveInfoInternalServerError struct {
	Payload *api_models.APIError
}

func (o *GETReceiveInfoInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/transfers/{id4n}/receiveInfo][%d] getReceiveInfoInternalServerError  %+v", 500, o.Payload)
}

func (o *GETReceiveInfoInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
