= ID4i CLI

ID4i Command Line Interface

You can use this application to ...

* ... perform manual tasks in ID4i
* ... include ID4i tasks in arbitrary shell scripts
* ... query ID4i manually or as part of existing workflows.

You can set global parameters in different locations (ordered by precedence):

* As command line parameter, e.g. --apikey or -k
*  Using environment variable under the "ID4I_" prefix, e.g. "ID4I_APIKEY"
* In a configuration file (properties, JSON, YAML, TOML, HCL formats are supported).
+
Default locations are ./.idi.<type> and ~/.id4i.<type> with <type> denoting the file format (json, yml, toml, hcl, properties)
You can specify a different file using the --config/-c parameter.

Refer to "id4i help" for available configuration parameters.


== Usage

[source]
```
include::doc/help.txt[]
```

[source]
```
include::doc/help-guids.txt[]
```

[source]
```
include::doc/help-history.txt[]
```

[source]
```
include::doc/help-storage.txt[]
```


== Development

=== Prerequisites

* Go 1.11.2
* Go Dep, get it w/ `go get -u -v github.com/golang/dep/cmd/dep`
* Docker, if you want to build the docker image. `v18.06.1-ce` and `v17.03.0-ce` are known to work

=== Build

* `git clone git@github.com:BlueRainSoftware/id4i-cli.git $GOPATH/src/github.com/BlueRainSoftware/id4i-cli`
* `cd $GOPATH/src/github.com/BlueRainSoftware/id4i-cli`
* `dep ensure -v`
* `go build -o id4i main.go`

==== Docker

To build the docker image, run `docker build . -t id4i:<my tag>`.

==== CI

CI Builds live at https://circleci.com/gh/BlueRainSoftware/workflows/id4i-cli, defined in `.circleci/config.yml`.
Note that currently, the build artifacts (binary and docker image) are not stored anywhere, so you probably
need to build it yourself. This will change, promise.`

=== Run

After building, you can run the binary w/ `./id4i`.

You can also run the ID4i CLI within Docker: `docker run id4i <args>`. e.g.
`docker run id4i help` or `docker run id4i info -h`

=== Test

TODO
