:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= ID4i CLI

ID4i Command Line Interface

You can use this application to ...

* ... perform manual tasks in ID4i
* ... include ID4i tasks in arbitrary shell scripts
* ... query ID4i manually or as part of existing workflows.

CAUTION: ID4i CLI is currently a work in progress and should not be used in production; at least not
without getting in touch first. More operations _will_ be added in the future.

ID4i CLI is configurable using environment variables, a variety of configuration files
and command line switches. See the <<Usage>> section or `id4i help` for details.

Since we do not have extensive experience in `golang`, we are thankful for contributions and/or bitching and nagging,
especially in combination with pointers to more idiomatic alternative implementations.


toc::[]

== Usage

=== Prerequisites

For the CLI to be able to communicate with ID4i, you need an ID4i API key.

Complete the following steps to get from zero to your first successful ID4i CLI operation:

. If you have not already done, register a user on ID4i. Use link:++https://sandbox.id4i.de/#/register++[Sandbox] for care-free experimenting,
and link:++https://backend.id4i.de/#/register++[Production] for production use.
. Create and activate an API key (the link:https://backend.id4i.de/docs/reference/en/reference.html#_preparation[development manual ] has more info and screenshots)
.. Navigate to `API Keys -> New API Key`
.. Note your API key secret and your API key ID
.. Activate the API key
. Figure out your organization's namespace (or even better, create a new one) on `Organizations`
. Configure the CLI to use your API key
.. EITHER set `ID4I_APIKEY`, `ID4I_SECRET`, `ID4I_BACKEND` and `ID4I_ORGANZATION` environment variables
.. OR use a configuration file in the current or your home directory named `.id4i.properties` (or `.json` or `.yml`)
and set the properties `apikey`, `secret`, `backend` and `organization` there
.. OR use command line flags for these parameters as described in <<Help>>
.. OR any combination of the above. You get the point.
. Give your API key the corresponding permissions required to carry out the task you want.
Go to the details page of your API key and set the permissions. You can learn about what happens in the
background in the link:https://sandbox.id4i.de/docs/reference/en/reference.html#_create_guids_code_2_code_and_learn_about_things_that_can_go_wrong[development manual].

You can either get a binary for your platform or run the ID4i CLI within Docker: `docker run bluerainsoftware/id4i <args>`. e.g.
`docker run bluerainsoftware/id4i help` or `docker run bluerainsoftware/id4i info -h`.

For details on how to configure the image with your API key and other required properties, see https://hub.docker.com/r/bluerainsoftware/id4i-cli/

=== Help


(statically generated using `update-readme.sh`)

== Development

If you need additional commands, feel free to jump in or let us know.

If you want to get involved, we classified some tasks as link:https://github.com/BlueRainSoftware/id4i-cli/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22[good first issues] to get you started.

=== Prerequisites

* Go 1.11.2
* Go Dep, get it w/ `go get -u -v github.com/golang/dep/cmd/dep`
* Docker, if you want to build the docker image. `v18.06.1-ce` and `v17.03.0-ce` are known to work
* If you want to scaffold new commands, the `cobra` generator will help you: `go get github.com/spf13/cobra/cobra`
* If you want to run the tests, you'll need `jq`: https://stedolan.github.io/

=== Adding new commands

We use the awesome `cobra` footnote:[https://github.com/spf13/cobra] and `viper` footnote:[https://github.com/spf13/viper] libraries.

To scaffold a new command, clone the repo and say `cobra add <my command> -p rootCmd`.

Open the generated command and implement your operation:

* Define your parameters in `init`.
* Validate your input, if required.
* Use the operations exposed in `ID4i` (from `rootCmd`) to call the backend.
* Use the `OutputResult` and `DieOnError` functions from `rootCmd` to report the result of your command.
* Add your command to `./update-readme.sh` so the `README` gets updated with the new command

You can find examples for each step in the existing commands.

If you want to debug the calls you are making, set the `DEBUG` environment variable to a non-empty value.
This will cause the HTTP calls to be logged to the console.

NOTE: Please don't forget to add tests for your new commands, see <<Test>>

=== Updating the API version

The API client is generated using `go-swagger` footnote:[https://github.com/go-swagger/go-swagger, https://goswagger.io/].

To update the client for the CLI, run `./generate-api-client.sh -c -d` from the project root. Note that `-d` installs `go-swagger`
locally and `-c` pulls the current API specification from ID4i production footnote:[https://backend.id4i.de/docs/swagger.json; use the corresponding URL for other environments, e.g. https://sandbox.id4i.de/docs/swagger.json]

Run the tests and make required corrections in the existing commands if applicable. The ID4i change logs footnote:[https://github.com/BlueRainSoftware/support/tree/master/changelog]
are probably helpful.

=== Build

* `git clone git@github.com:BlueRainSoftware/id4i-cli.git $GOPATH/src/github.com/BlueRainSoftware/id4i-cli`
* `cd $GOPATH/src/github.com/BlueRainSoftware/id4i-cli`
* `dep ensure -v`
* `go build -o id4i main.go`
* Update the `README` with the current help contents: `./update-readme.sh`

==== Docker

To build the docker image, run `docker build . -t id4i:<my tag>`.

The README shown on https://hub.docker.com/r/bluerainsoftware/id4i-cli/[DockerHub] is the `README.md` file
in this repository.

==== CI

CI Builds live on link:https://circleci.com/gh/BlueRainSoftware/workflows/id4i-cli[CircleCI], defined in `.circleci/config.yml`.
Note that currently, the build artifacts (binary and docker image) are not stored anywhere, so you probably
need to build it yourself. This will change, promise.

The docker image is built/pushed using the automatic builds on docker hub. The master branch is tagged `latest`, the
develop branch `develop`. Tags starting with `v` are used as releases using the tag as version for the image.

=== Run

After building, you can run the binary w/ `./id4i`.

=== Test

Integration tests live in `test/tests`. The `preflight.sh` script creates a user, saves the required information
for `id4i` configuration to a temporary file and creates an `id4i` configuration file.
It can also be used to download the testing framework (`bats` footnote:[https://github.com/sstephenson/bats]) and
to build the binary.

----
$ ./run-tests.sh -h
Run ID4i CLI tests
Usage: run-tests.sh [-h] [-v] [-i] [-p] [-c] [-b] [-t]
  -h	help - Show this help message.
  -v	version - Show version information.
  -i	install - Install Prerequisites
  -p	preflight - Run preflight script (provision ID4i test user)
  -c	cleanup - Clean up test results after successful tests
  -b	build - Build ID4i binary before testing (requires Go)
  -t	tap-format - Use TAP format test output (for CI reports)
----

NOTE: The tests always run against `id4i-develop` as of now.
