:toc:
:toc-placement!:

= ID4i CLI

ID4i Command Line Interface

You can use this application to ...

* ... perform manual tasks in ID4i
* ... include ID4i tasks in arbitrary shell scripts
* ... query ID4i manually or as part of existing workflows.

WARNING: ID4i CLI is currently a work in progress and should not be used in production; at least not
without getting in touch first. More operations _will_ be added in the future.

ID4i CLI is configurable using environment variables, a variety of configuration files
and command line switches. See the <<Usage>> section or `id4i help` for details.

TIP: If you need addtional commands

toc::[]

== Usage

=== Prerequisites


=== Help

[source]
```
include::doc/help.txt[]
```

[source]
```
include::doc/help-guids.txt[]
```

[source]
```
include::doc/help-history.txt[]
```

[source]
```
include::doc/help-storage.txt[]
```


== Development

=== Prerequisites

* Go 1.11.2
* Go Dep, get it w/ `go get -u -v github.com/golang/dep/cmd/dep`
* Docker, if you want to build the docker image. `v18.06.1-ce` and `v17.03.0-ce` are known to work
* If you want to scaffold new commands, the `cobra` generator will help you: `go get github.com/spf13/cobra/cobra

=== Build

* `git clone git@github.com:BlueRainSoftware/id4i-cli.git $GOPATH/src/github.com/BlueRainSoftware/id4i-cli`
* `cd $GOPATH/src/github.com/BlueRainSoftware/id4i-cli`
* `dep ensure -v`
* `go build -o id4i main.go`

=== Adding new commands

We use the awesome `cobra` footnote:[https://github.com/spf13/cobra] and `viper` footnote:[https://github.com/spf13/viper] libraries.

To scaffold a new command, clone the repo and say `cobra add <my command> -p rootCmd`

==== Docker

To build the docker image, run `docker build . -t id4i:<my tag>`.

==== CI

CI Builds live at https://circleci.com/gh/BlueRainSoftware/workflows/id4i-cli, defined in `.circleci/config.yml`.
Note that currently, the build artifacts (binary and docker image) are not stored anywhere, so you probably
need to build it yourself. This will change, promise.`

=== Run

After building, you can run the binary w/ `./id4i`.

You can also run the ID4i CLI within Docker: `docker run id4i <args>`. e.g.
`docker run id4i help` or `docker run id4i info -h`

=== Test

TODO
