:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= ID4i CLI

ID4i Command Line Interface

You can use this application to ...

* ... perform manual tasks in ID4i
* ... include ID4i tasks in arbitrary shell scripts
* ... query ID4i manually or as part of existing workflows.

CAUTION: ID4i CLI is currently a work in progress and should not be used in production; at least not
without getting in touch first. More operations _will_ be added in the future.

ID4i CLI is configurable using environment variables, a variety of configuration files
and command line switches. See the <<Usage>> section or `id4i help` for details.

Since we do not have extensive experience in `golang`, we are thankful for contributions and/or bitching and nagging,
especially in combination with pointers to more idiomatic alternative implementations.


toc::[]

== Usage

=== Prerequisites

WARNING: Describe how to add a user and an API key

=== Help


(statically generated using `update-readme.sh`)

TESTME

== Development

If you need additional commands, feel free to jump in or let us know.

If you want to get involved, https://github.com/BlueRainSoftware/id4i-cli/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22 has good issues to get you started.


=== Prerequisites

* Go 1.11.2
* Go Dep, get it w/ `go get -u -v github.com/golang/dep/cmd/dep`
* Docker, if you want to build the docker image. `v18.06.1-ce` and `v17.03.0-ce` are known to work
* If you want to scaffold new commands, the `cobra` generator will help you: `go get github.com/spf13/cobra/cobra

=== Build

* `git clone git@github.com:BlueRainSoftware/id4i-cli.git $GOPATH/src/github.com/BlueRainSoftware/id4i-cli`
* `cd $GOPATH/src/github.com/BlueRainSoftware/id4i-cli`
* `dep ensure -v`
* `go build -o id4i main.go`
* Update the `README` with the current help contents: `./update-readme.sh`

=== Adding new commands

We use the awesome `cobra` footnote:[https://github.com/spf13/cobra] and `viper` footnote:[https://github.com/spf13/viper] libraries.

To scaffold a new command, clone the repo and say `cobra add <my command> -p rootCmd`.

Open the generated command and implement your operation:

* Define your parameters in `init`.
* Validate your input, if required.
* Use the operations exposed in `ID4i` (from `rootCmd`) to call the backend.
* Use the `OutputResult` and `DieOnError` functions from `rootCmd` to report the result of your command.
* Add your command to `./update-readme.sh` so the `README` gets updated with the new command

You can find examples for each step in the existing commands.

==== Updating the API version

The API client is generated using `go-swagger` footnote:[https://github.com/go-swagger/go-swagger, https://goswagger.io/].

To update the client for the CLI, run `./generate-api-client.sh -c -d` from the project root. Note that `-d` installs `go-swagger`
locally and `-c` pulls the current API specification from ID4i production footnote:[https://backend.id4i.de/docs/swagger.json; use the corresponding URL for other environments, e.g. https://sandbox.id4i.de/docs/swagger.json]

Run the tests and make required corrections in the existing commands if applicable. The ID4i change logs footnote:[https://github.com/BlueRainSoftware/support/tree/master/changelog]
are probably helpful.

==== Docker

To build the docker image, run `docker build . -t id4i:<my tag>`.

==== CI

CI Builds live at https://circleci.com/gh/BlueRainSoftware/workflows/id4i-cli, defined in `.circleci/config.yml`.
Note that currently, the build artifacts (binary and docker image) are not stored anywhere, so you probably
need to build it yourself. This will change, promise.

=== Run

After building, you can run the binary w/ `./id4i`.

You can also run the ID4i CLI within Docker: `docker run id4i <args>`. e.g.
`docker run id4i help` or `docker run id4i info -h`

=== Test

*TODO*

* Generate user w/ API key on develop (existing UI tests or curl)
* Have a shell script using the cli to carry out all operations
* Have the script run in CI
