// Code generated by go-swagger; DO NOT EDIT.

package routing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	api_models "github.com/BlueRainSoftware/id4i-cli/api_models"
)

// NewUpdateRoutingFileParams creates a new UpdateRoutingFileParams object
// with the default values initialized.
func NewUpdateRoutingFileParams() *UpdateRoutingFileParams {
	var ()
	return &UpdateRoutingFileParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateRoutingFileParamsWithTimeout creates a new UpdateRoutingFileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateRoutingFileParamsWithTimeout(timeout time.Duration) *UpdateRoutingFileParams {
	var ()
	return &UpdateRoutingFileParams{

		timeout: timeout,
	}
}

// NewUpdateRoutingFileParamsWithContext creates a new UpdateRoutingFileParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateRoutingFileParamsWithContext(ctx context.Context) *UpdateRoutingFileParams {
	var ()
	return &UpdateRoutingFileParams{

		Context: ctx,
	}
}

// NewUpdateRoutingFileParamsWithHTTPClient creates a new UpdateRoutingFileParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateRoutingFileParamsWithHTTPClient(client *http.Client) *UpdateRoutingFileParams {
	var ()
	return &UpdateRoutingFileParams{
		HTTPClient: client,
	}
}

/*UpdateRoutingFileParams contains all the parameters to send to the API endpoint
for the update routing file operation typically these are written to a http.Request
*/
type UpdateRoutingFileParams struct {

	/*ID4N
	  id4n

	*/
	ID4N string
	/*Rfr
	  rfr

	*/
	Rfr *api_models.RoutingFileRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update routing file params
func (o *UpdateRoutingFileParams) WithTimeout(timeout time.Duration) *UpdateRoutingFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update routing file params
func (o *UpdateRoutingFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update routing file params
func (o *UpdateRoutingFileParams) WithContext(ctx context.Context) *UpdateRoutingFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update routing file params
func (o *UpdateRoutingFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update routing file params
func (o *UpdateRoutingFileParams) WithHTTPClient(client *http.Client) *UpdateRoutingFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update routing file params
func (o *UpdateRoutingFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID4N adds the id4n to the update routing file params
func (o *UpdateRoutingFileParams) WithID4N(id4n string) *UpdateRoutingFileParams {
	o.SetID4N(id4n)
	return o
}

// SetID4N adds the id4n to the update routing file params
func (o *UpdateRoutingFileParams) SetID4N(id4n string) {
	o.ID4N = id4n
}

// WithRfr adds the rfr to the update routing file params
func (o *UpdateRoutingFileParams) WithRfr(rfr *api_models.RoutingFileRequest) *UpdateRoutingFileParams {
	o.SetRfr(rfr)
	return o
}

// SetRfr adds the rfr to the update routing file params
func (o *UpdateRoutingFileParams) SetRfr(rfr *api_models.RoutingFileRequest) {
	o.Rfr = rfr
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateRoutingFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id4n
	if err := r.SetPathParam("id4n", o.ID4N); err != nil {
		return err
	}

	if o.Rfr != nil {
		if err := r.SetBodyParam(o.Rfr); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
