// Code generated by go-swagger; DO NOT EDIT.

package meta_information

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewApplicationInfoParams creates a new ApplicationInfoParams object
// with the default values initialized.
func NewApplicationInfoParams() *ApplicationInfoParams {

	return &ApplicationInfoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewApplicationInfoParamsWithTimeout creates a new ApplicationInfoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewApplicationInfoParamsWithTimeout(timeout time.Duration) *ApplicationInfoParams {

	return &ApplicationInfoParams{

		timeout: timeout,
	}
}

// NewApplicationInfoParamsWithContext creates a new ApplicationInfoParams object
// with the default values initialized, and the ability to set a context for a request
func NewApplicationInfoParamsWithContext(ctx context.Context) *ApplicationInfoParams {

	return &ApplicationInfoParams{

		Context: ctx,
	}
}

// NewApplicationInfoParamsWithHTTPClient creates a new ApplicationInfoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewApplicationInfoParamsWithHTTPClient(client *http.Client) *ApplicationInfoParams {

	return &ApplicationInfoParams{
		HTTPClient: client,
	}
}

/*ApplicationInfoParams contains all the parameters to send to the API endpoint
for the application info operation typically these are written to a http.Request
*/
type ApplicationInfoParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the application info params
func (o *ApplicationInfoParams) WithTimeout(timeout time.Duration) *ApplicationInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the application info params
func (o *ApplicationInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the application info params
func (o *ApplicationInfoParams) WithContext(ctx context.Context) *ApplicationInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the application info params
func (o *ApplicationInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the application info params
func (o *ApplicationInfoParams) WithHTTPClient(client *http.Client) *ApplicationInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the application info params
func (o *ApplicationInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ApplicationInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
