// Code generated by go-swagger; DO NOT EDIT.

package api_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGETAPIKeyParams creates a new GETAPIKeyParams object
// with the default values initialized.
func NewGETAPIKeyParams() *GETAPIKeyParams {
	var ()
	return &GETAPIKeyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGETAPIKeyParamsWithTimeout creates a new GETAPIKeyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGETAPIKeyParamsWithTimeout(timeout time.Duration) *GETAPIKeyParams {
	var ()
	return &GETAPIKeyParams{

		timeout: timeout,
	}
}

// NewGETAPIKeyParamsWithContext creates a new GETAPIKeyParams object
// with the default values initialized, and the ability to set a context for a request
func NewGETAPIKeyParamsWithContext(ctx context.Context) *GETAPIKeyParams {
	var ()
	return &GETAPIKeyParams{

		Context: ctx,
	}
}

// NewGETAPIKeyParamsWithHTTPClient creates a new GETAPIKeyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGETAPIKeyParamsWithHTTPClient(client *http.Client) *GETAPIKeyParams {
	var ()
	return &GETAPIKeyParams{
		HTTPClient: client,
	}
}

/*GETAPIKeyParams contains all the parameters to send to the API endpoint
for the get Api key operation typically these are written to a http.Request
*/
type GETAPIKeyParams struct {

	/*Key
	  The API key to show.

	*/
	Key string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get Api key params
func (o *GETAPIKeyParams) WithTimeout(timeout time.Duration) *GETAPIKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get Api key params
func (o *GETAPIKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get Api key params
func (o *GETAPIKeyParams) WithContext(ctx context.Context) *GETAPIKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get Api key params
func (o *GETAPIKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get Api key params
func (o *GETAPIKeyParams) WithHTTPClient(client *http.Client) *GETAPIKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get Api key params
func (o *GETAPIKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKey adds the key to the get Api key params
func (o *GETAPIKeyParams) WithKey(key string) *GETAPIKeyParams {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the get Api key params
func (o *GETAPIKeyParams) SetKey(key string) {
	o.Key = key
}

// WriteToRequest writes these params to a swagger request
func (o *GETAPIKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param key
	if err := r.SetPathParam("key", o.Key); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
