// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteOrganizationBillingAddressParams creates a new DeleteOrganizationBillingAddressParams object
// with the default values initialized.
func NewDeleteOrganizationBillingAddressParams() *DeleteOrganizationBillingAddressParams {
	var ()
	return &DeleteOrganizationBillingAddressParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteOrganizationBillingAddressParamsWithTimeout creates a new DeleteOrganizationBillingAddressParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteOrganizationBillingAddressParamsWithTimeout(timeout time.Duration) *DeleteOrganizationBillingAddressParams {
	var ()
	return &DeleteOrganizationBillingAddressParams{

		timeout: timeout,
	}
}

// NewDeleteOrganizationBillingAddressParamsWithContext creates a new DeleteOrganizationBillingAddressParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteOrganizationBillingAddressParamsWithContext(ctx context.Context) *DeleteOrganizationBillingAddressParams {
	var ()
	return &DeleteOrganizationBillingAddressParams{

		Context: ctx,
	}
}

// NewDeleteOrganizationBillingAddressParamsWithHTTPClient creates a new DeleteOrganizationBillingAddressParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteOrganizationBillingAddressParamsWithHTTPClient(client *http.Client) *DeleteOrganizationBillingAddressParams {
	var ()
	return &DeleteOrganizationBillingAddressParams{
		HTTPClient: client,
	}
}

/*DeleteOrganizationBillingAddressParams contains all the parameters to send to the API endpoint
for the delete organization billing address operation typically these are written to a http.Request
*/
type DeleteOrganizationBillingAddressParams struct {

	/*OrganizationID
	  organizationId

	*/
	OrganizationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete organization billing address params
func (o *DeleteOrganizationBillingAddressParams) WithTimeout(timeout time.Duration) *DeleteOrganizationBillingAddressParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete organization billing address params
func (o *DeleteOrganizationBillingAddressParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete organization billing address params
func (o *DeleteOrganizationBillingAddressParams) WithContext(ctx context.Context) *DeleteOrganizationBillingAddressParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete organization billing address params
func (o *DeleteOrganizationBillingAddressParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete organization billing address params
func (o *DeleteOrganizationBillingAddressParams) WithHTTPClient(client *http.Client) *DeleteOrganizationBillingAddressParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete organization billing address params
func (o *DeleteOrganizationBillingAddressParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganizationID adds the organizationID to the delete organization billing address params
func (o *DeleteOrganizationBillingAddressParams) WithOrganizationID(organizationID string) *DeleteOrganizationBillingAddressParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the delete organization billing address params
func (o *DeleteOrganizationBillingAddressParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteOrganizationBillingAddressParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
