// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFindOrganizationParams creates a new FindOrganizationParams object
// with the default values initialized.
func NewFindOrganizationParams() *FindOrganizationParams {
	var ()
	return &FindOrganizationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFindOrganizationParamsWithTimeout creates a new FindOrganizationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFindOrganizationParamsWithTimeout(timeout time.Duration) *FindOrganizationParams {
	var ()
	return &FindOrganizationParams{

		timeout: timeout,
	}
}

// NewFindOrganizationParamsWithContext creates a new FindOrganizationParams object
// with the default values initialized, and the ability to set a context for a request
func NewFindOrganizationParamsWithContext(ctx context.Context) *FindOrganizationParams {
	var ()
	return &FindOrganizationParams{

		Context: ctx,
	}
}

// NewFindOrganizationParamsWithHTTPClient creates a new FindOrganizationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFindOrganizationParamsWithHTTPClient(client *http.Client) *FindOrganizationParams {
	var ()
	return &FindOrganizationParams{
		HTTPClient: client,
	}
}

/*FindOrganizationParams contains all the parameters to send to the API endpoint
for the find organization operation typically these are written to a http.Request
*/
type FindOrganizationParams struct {

	/*OrganizationID
	  The namespace of the organization to be retrieved.

	*/
	OrganizationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the find organization params
func (o *FindOrganizationParams) WithTimeout(timeout time.Duration) *FindOrganizationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find organization params
func (o *FindOrganizationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find organization params
func (o *FindOrganizationParams) WithContext(ctx context.Context) *FindOrganizationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find organization params
func (o *FindOrganizationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find organization params
func (o *FindOrganizationParams) WithHTTPClient(client *http.Client) *FindOrganizationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find organization params
func (o *FindOrganizationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganizationID adds the organizationID to the find organization params
func (o *FindOrganizationParams) WithOrganizationID(organizationID string) *FindOrganizationParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the find organization params
func (o *FindOrganizationParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WriteToRequest writes these params to a swagger request
func (o *FindOrganizationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
