// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	api_models "github.com/BlueRainSoftware/id4i-cli/api_models"
)

// FindOrganizationBillingAddressReader is a Reader for the FindOrganizationBillingAddress structure.
type FindOrganizationBillingAddressReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindOrganizationBillingAddressReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewFindOrganizationBillingAddressOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 202:
		result := NewFindOrganizationBillingAddressAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewFindOrganizationBillingAddressUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewFindOrganizationBillingAddressForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewFindOrganizationBillingAddressNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 405:
		result := NewFindOrganizationBillingAddressMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 406:
		result := NewFindOrganizationBillingAddressNotAcceptable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 415:
		result := NewFindOrganizationBillingAddressUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewFindOrganizationBillingAddressInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewFindOrganizationBillingAddressOK creates a FindOrganizationBillingAddressOK with default headers values
func NewFindOrganizationBillingAddressOK() *FindOrganizationBillingAddressOK {
	return &FindOrganizationBillingAddressOK{}
}

/*FindOrganizationBillingAddressOK handles this case with default header values.

OK
*/
type FindOrganizationBillingAddressOK struct {
	Payload *api_models.OrganizationAddress
}

func (o *FindOrganizationBillingAddressOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/organizations/{organizationId}/addresses/billing][%d] findOrganizationBillingAddressOK  %+v", 200, o.Payload)
}

func (o *FindOrganizationBillingAddressOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.OrganizationAddress)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindOrganizationBillingAddressAccepted creates a FindOrganizationBillingAddressAccepted with default headers values
func NewFindOrganizationBillingAddressAccepted() *FindOrganizationBillingAddressAccepted {
	return &FindOrganizationBillingAddressAccepted{}
}

/*FindOrganizationBillingAddressAccepted handles this case with default header values.

Accepted
*/
type FindOrganizationBillingAddressAccepted struct {
}

func (o *FindOrganizationBillingAddressAccepted) Error() string {
	return fmt.Sprintf("[GET /api/v1/organizations/{organizationId}/addresses/billing][%d] findOrganizationBillingAddressAccepted ", 202)
}

func (o *FindOrganizationBillingAddressAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewFindOrganizationBillingAddressUnauthorized creates a FindOrganizationBillingAddressUnauthorized with default headers values
func NewFindOrganizationBillingAddressUnauthorized() *FindOrganizationBillingAddressUnauthorized {
	return &FindOrganizationBillingAddressUnauthorized{}
}

/*FindOrganizationBillingAddressUnauthorized handles this case with default header values.

Unauthorized
*/
type FindOrganizationBillingAddressUnauthorized struct {
	Payload *api_models.APIError
}

func (o *FindOrganizationBillingAddressUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1/organizations/{organizationId}/addresses/billing][%d] findOrganizationBillingAddressUnauthorized  %+v", 401, o.Payload)
}

func (o *FindOrganizationBillingAddressUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindOrganizationBillingAddressForbidden creates a FindOrganizationBillingAddressForbidden with default headers values
func NewFindOrganizationBillingAddressForbidden() *FindOrganizationBillingAddressForbidden {
	return &FindOrganizationBillingAddressForbidden{}
}

/*FindOrganizationBillingAddressForbidden handles this case with default header values.

Forbidden
*/
type FindOrganizationBillingAddressForbidden struct {
	Payload *api_models.APIError
}

func (o *FindOrganizationBillingAddressForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/organizations/{organizationId}/addresses/billing][%d] findOrganizationBillingAddressForbidden  %+v", 403, o.Payload)
}

func (o *FindOrganizationBillingAddressForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindOrganizationBillingAddressNotFound creates a FindOrganizationBillingAddressNotFound with default headers values
func NewFindOrganizationBillingAddressNotFound() *FindOrganizationBillingAddressNotFound {
	return &FindOrganizationBillingAddressNotFound{}
}

/*FindOrganizationBillingAddressNotFound handles this case with default header values.

Not Found
*/
type FindOrganizationBillingAddressNotFound struct {
	Payload *api_models.APIError
}

func (o *FindOrganizationBillingAddressNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/organizations/{organizationId}/addresses/billing][%d] findOrganizationBillingAddressNotFound  %+v", 404, o.Payload)
}

func (o *FindOrganizationBillingAddressNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindOrganizationBillingAddressMethodNotAllowed creates a FindOrganizationBillingAddressMethodNotAllowed with default headers values
func NewFindOrganizationBillingAddressMethodNotAllowed() *FindOrganizationBillingAddressMethodNotAllowed {
	return &FindOrganizationBillingAddressMethodNotAllowed{}
}

/*FindOrganizationBillingAddressMethodNotAllowed handles this case with default header values.

Method not allowed
*/
type FindOrganizationBillingAddressMethodNotAllowed struct {
	Payload *api_models.APIError
}

func (o *FindOrganizationBillingAddressMethodNotAllowed) Error() string {
	return fmt.Sprintf("[GET /api/v1/organizations/{organizationId}/addresses/billing][%d] findOrganizationBillingAddressMethodNotAllowed  %+v", 405, o.Payload)
}

func (o *FindOrganizationBillingAddressMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindOrganizationBillingAddressNotAcceptable creates a FindOrganizationBillingAddressNotAcceptable with default headers values
func NewFindOrganizationBillingAddressNotAcceptable() *FindOrganizationBillingAddressNotAcceptable {
	return &FindOrganizationBillingAddressNotAcceptable{}
}

/*FindOrganizationBillingAddressNotAcceptable handles this case with default header values.

Not Acceptable
*/
type FindOrganizationBillingAddressNotAcceptable struct {
	Payload *api_models.APIError
}

func (o *FindOrganizationBillingAddressNotAcceptable) Error() string {
	return fmt.Sprintf("[GET /api/v1/organizations/{organizationId}/addresses/billing][%d] findOrganizationBillingAddressNotAcceptable  %+v", 406, o.Payload)
}

func (o *FindOrganizationBillingAddressNotAcceptable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindOrganizationBillingAddressUnsupportedMediaType creates a FindOrganizationBillingAddressUnsupportedMediaType with default headers values
func NewFindOrganizationBillingAddressUnsupportedMediaType() *FindOrganizationBillingAddressUnsupportedMediaType {
	return &FindOrganizationBillingAddressUnsupportedMediaType{}
}

/*FindOrganizationBillingAddressUnsupportedMediaType handles this case with default header values.

Unsupported Media Type
*/
type FindOrganizationBillingAddressUnsupportedMediaType struct {
	Payload *api_models.APIError
}

func (o *FindOrganizationBillingAddressUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[GET /api/v1/organizations/{organizationId}/addresses/billing][%d] findOrganizationBillingAddressUnsupportedMediaType  %+v", 415, o.Payload)
}

func (o *FindOrganizationBillingAddressUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindOrganizationBillingAddressInternalServerError creates a FindOrganizationBillingAddressInternalServerError with default headers values
func NewFindOrganizationBillingAddressInternalServerError() *FindOrganizationBillingAddressInternalServerError {
	return &FindOrganizationBillingAddressInternalServerError{}
}

/*FindOrganizationBillingAddressInternalServerError handles this case with default header values.

Internal Server Error
*/
type FindOrganizationBillingAddressInternalServerError struct {
	Payload *api_models.APIError
}

func (o *FindOrganizationBillingAddressInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/organizations/{organizationId}/addresses/billing][%d] findOrganizationBillingAddressInternalServerError  %+v", 500, o.Payload)
}

func (o *FindOrganizationBillingAddressInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
