// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGETOrganizationPrivilegesParams creates a new GETOrganizationPrivilegesParams object
// with the default values initialized.
func NewGETOrganizationPrivilegesParams() *GETOrganizationPrivilegesParams {
	var ()
	return &GETOrganizationPrivilegesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGETOrganizationPrivilegesParamsWithTimeout creates a new GETOrganizationPrivilegesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGETOrganizationPrivilegesParamsWithTimeout(timeout time.Duration) *GETOrganizationPrivilegesParams {
	var ()
	return &GETOrganizationPrivilegesParams{

		timeout: timeout,
	}
}

// NewGETOrganizationPrivilegesParamsWithContext creates a new GETOrganizationPrivilegesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGETOrganizationPrivilegesParamsWithContext(ctx context.Context) *GETOrganizationPrivilegesParams {
	var ()
	return &GETOrganizationPrivilegesParams{

		Context: ctx,
	}
}

// NewGETOrganizationPrivilegesParamsWithHTTPClient creates a new GETOrganizationPrivilegesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGETOrganizationPrivilegesParamsWithHTTPClient(client *http.Client) *GETOrganizationPrivilegesParams {
	var ()
	return &GETOrganizationPrivilegesParams{
		HTTPClient: client,
	}
}

/*GETOrganizationPrivilegesParams contains all the parameters to send to the API endpoint
for the get organization privileges operation typically these are written to a http.Request
*/
type GETOrganizationPrivilegesParams struct {

	/*OrganizationID
	  The namespace of the organization

	*/
	OrganizationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get organization privileges params
func (o *GETOrganizationPrivilegesParams) WithTimeout(timeout time.Duration) *GETOrganizationPrivilegesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organization privileges params
func (o *GETOrganizationPrivilegesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organization privileges params
func (o *GETOrganizationPrivilegesParams) WithContext(ctx context.Context) *GETOrganizationPrivilegesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organization privileges params
func (o *GETOrganizationPrivilegesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organization privileges params
func (o *GETOrganizationPrivilegesParams) WithHTTPClient(client *http.Client) *GETOrganizationPrivilegesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organization privileges params
func (o *GETOrganizationPrivilegesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganizationID adds the organizationID to the get organization privileges params
func (o *GETOrganizationPrivilegesParams) WithOrganizationID(organizationID string) *GETOrganizationPrivilegesParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the get organization privileges params
func (o *GETOrganizationPrivilegesParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WriteToRequest writes these params to a swagger request
func (o *GETOrganizationPrivilegesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
