// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	api_models "github.com/BlueRainSoftware/id4i-cli/api_models"
)

// DeleteDocumentReader is a Reader for the DeleteDocument structure.
type DeleteDocumentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDocumentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteDocumentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteDocumentBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteDocumentUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteDocumentForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteDocumentNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteDocumentInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteDocumentOK creates a DeleteDocumentOK with default headers values
func NewDeleteDocumentOK() *DeleteDocumentOK {
	return &DeleteDocumentOK{}
}

/*DeleteDocumentOK handles this case with default header values.

OK
*/
type DeleteDocumentOK struct {
	Payload *api_models.ResponseEntity
}

func (o *DeleteDocumentOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/documents/{id4n}/{organizationId}/{fileName}][%d] deleteDocumentOK  %+v", 200, o.Payload)
}

func (o *DeleteDocumentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.ResponseEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDocumentBadRequest creates a DeleteDocumentBadRequest with default headers values
func NewDeleteDocumentBadRequest() *DeleteDocumentBadRequest {
	return &DeleteDocumentBadRequest{}
}

/*DeleteDocumentBadRequest handles this case with default header values.

Bad Request
*/
type DeleteDocumentBadRequest struct {
	Payload *api_models.APIError
}

func (o *DeleteDocumentBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/documents/{id4n}/{organizationId}/{fileName}][%d] deleteDocumentBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteDocumentBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDocumentUnauthorized creates a DeleteDocumentUnauthorized with default headers values
func NewDeleteDocumentUnauthorized() *DeleteDocumentUnauthorized {
	return &DeleteDocumentUnauthorized{}
}

/*DeleteDocumentUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteDocumentUnauthorized struct {
	Payload *api_models.APIError
}

func (o *DeleteDocumentUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/documents/{id4n}/{organizationId}/{fileName}][%d] deleteDocumentUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteDocumentUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDocumentForbidden creates a DeleteDocumentForbidden with default headers values
func NewDeleteDocumentForbidden() *DeleteDocumentForbidden {
	return &DeleteDocumentForbidden{}
}

/*DeleteDocumentForbidden handles this case with default header values.

Forbidden
*/
type DeleteDocumentForbidden struct {
	Payload *api_models.APIError
}

func (o *DeleteDocumentForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/documents/{id4n}/{organizationId}/{fileName}][%d] deleteDocumentForbidden  %+v", 403, o.Payload)
}

func (o *DeleteDocumentForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDocumentNotFound creates a DeleteDocumentNotFound with default headers values
func NewDeleteDocumentNotFound() *DeleteDocumentNotFound {
	return &DeleteDocumentNotFound{}
}

/*DeleteDocumentNotFound handles this case with default header values.

Not Found
*/
type DeleteDocumentNotFound struct {
	Payload *api_models.APIError
}

func (o *DeleteDocumentNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/documents/{id4n}/{organizationId}/{fileName}][%d] deleteDocumentNotFound  %+v", 404, o.Payload)
}

func (o *DeleteDocumentNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDocumentInternalServerError creates a DeleteDocumentInternalServerError with default headers values
func NewDeleteDocumentInternalServerError() *DeleteDocumentInternalServerError {
	return &DeleteDocumentInternalServerError{}
}

/*DeleteDocumentInternalServerError handles this case with default header values.

Internal Server Error
*/
type DeleteDocumentInternalServerError struct {
	Payload *api_models.APIError
}

func (o *DeleteDocumentInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/documents/{id4n}/{organizationId}/{fileName}][%d] deleteDocumentInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteDocumentInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
