// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteDocumentParams creates a new DeleteDocumentParams object
// with the default values initialized.
func NewDeleteDocumentParams() *DeleteDocumentParams {
	var ()
	return &DeleteDocumentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDocumentParamsWithTimeout creates a new DeleteDocumentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteDocumentParamsWithTimeout(timeout time.Duration) *DeleteDocumentParams {
	var ()
	return &DeleteDocumentParams{

		timeout: timeout,
	}
}

// NewDeleteDocumentParamsWithContext creates a new DeleteDocumentParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteDocumentParamsWithContext(ctx context.Context) *DeleteDocumentParams {
	var ()
	return &DeleteDocumentParams{

		Context: ctx,
	}
}

// NewDeleteDocumentParamsWithHTTPClient creates a new DeleteDocumentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteDocumentParamsWithHTTPClient(client *http.Client) *DeleteDocumentParams {
	var ()
	return &DeleteDocumentParams{
		HTTPClient: client,
	}
}

/*DeleteDocumentParams contains all the parameters to send to the API endpoint
for the delete document operation typically these are written to a http.Request
*/
type DeleteDocumentParams struct {

	/*FileName
	  fileName

	*/
	FileName string
	/*ID4N
	  id4n

	*/
	ID4N string
	/*OrganizationID
	  organizationId

	*/
	OrganizationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete document params
func (o *DeleteDocumentParams) WithTimeout(timeout time.Duration) *DeleteDocumentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete document params
func (o *DeleteDocumentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete document params
func (o *DeleteDocumentParams) WithContext(ctx context.Context) *DeleteDocumentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete document params
func (o *DeleteDocumentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete document params
func (o *DeleteDocumentParams) WithHTTPClient(client *http.Client) *DeleteDocumentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete document params
func (o *DeleteDocumentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFileName adds the fileName to the delete document params
func (o *DeleteDocumentParams) WithFileName(fileName string) *DeleteDocumentParams {
	o.SetFileName(fileName)
	return o
}

// SetFileName adds the fileName to the delete document params
func (o *DeleteDocumentParams) SetFileName(fileName string) {
	o.FileName = fileName
}

// WithID4N adds the id4n to the delete document params
func (o *DeleteDocumentParams) WithID4N(id4n string) *DeleteDocumentParams {
	o.SetID4N(id4n)
	return o
}

// SetID4N adds the id4n to the delete document params
func (o *DeleteDocumentParams) SetID4N(id4n string) {
	o.ID4N = id4n
}

// WithOrganizationID adds the organizationID to the delete document params
func (o *DeleteDocumentParams) WithOrganizationID(organizationID string) *DeleteDocumentParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the delete document params
func (o *DeleteDocumentParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDocumentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param fileName
	if err := r.SetPathParam("fileName", o.FileName); err != nil {
		return err
	}

	// path param id4n
	if err := r.SetPathParam("id4n", o.ID4N); err != nil {
		return err
	}

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
