// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListAllDocumentsParams creates a new ListAllDocumentsParams object
// with the default values initialized.
func NewListAllDocumentsParams() *ListAllDocumentsParams {
	var ()
	return &ListAllDocumentsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListAllDocumentsParamsWithTimeout creates a new ListAllDocumentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListAllDocumentsParamsWithTimeout(timeout time.Duration) *ListAllDocumentsParams {
	var ()
	return &ListAllDocumentsParams{

		timeout: timeout,
	}
}

// NewListAllDocumentsParamsWithContext creates a new ListAllDocumentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListAllDocumentsParamsWithContext(ctx context.Context) *ListAllDocumentsParams {
	var ()
	return &ListAllDocumentsParams{

		Context: ctx,
	}
}

// NewListAllDocumentsParamsWithHTTPClient creates a new ListAllDocumentsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListAllDocumentsParamsWithHTTPClient(client *http.Client) *ListAllDocumentsParams {
	var ()
	return &ListAllDocumentsParams{
		HTTPClient: client,
	}
}

/*ListAllDocumentsParams contains all the parameters to send to the API endpoint
for the list all documents operation typically these are written to a http.Request
*/
type ListAllDocumentsParams struct {

	/*ID4N
	  id4n

	*/
	ID4N string
	/*Limit
	  The maximum count of returned elements

	*/
	Limit *int32
	/*Offset
	  Start with the n-th element

	*/
	Offset *int32
	/*Owner
	  Filter by owner organization

	*/
	Owner *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list all documents params
func (o *ListAllDocumentsParams) WithTimeout(timeout time.Duration) *ListAllDocumentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list all documents params
func (o *ListAllDocumentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list all documents params
func (o *ListAllDocumentsParams) WithContext(ctx context.Context) *ListAllDocumentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list all documents params
func (o *ListAllDocumentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list all documents params
func (o *ListAllDocumentsParams) WithHTTPClient(client *http.Client) *ListAllDocumentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list all documents params
func (o *ListAllDocumentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID4N adds the id4n to the list all documents params
func (o *ListAllDocumentsParams) WithID4N(id4n string) *ListAllDocumentsParams {
	o.SetID4N(id4n)
	return o
}

// SetID4N adds the id4n to the list all documents params
func (o *ListAllDocumentsParams) SetID4N(id4n string) {
	o.ID4N = id4n
}

// WithLimit adds the limit to the list all documents params
func (o *ListAllDocumentsParams) WithLimit(limit *int32) *ListAllDocumentsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list all documents params
func (o *ListAllDocumentsParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithOffset adds the offset to the list all documents params
func (o *ListAllDocumentsParams) WithOffset(offset *int32) *ListAllDocumentsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the list all documents params
func (o *ListAllDocumentsParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WithOwner adds the owner to the list all documents params
func (o *ListAllDocumentsParams) WithOwner(owner *string) *ListAllDocumentsParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the list all documents params
func (o *ListAllDocumentsParams) SetOwner(owner *string) {
	o.Owner = owner
}

// WriteToRequest writes these params to a swagger request
func (o *ListAllDocumentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id4n
	if err := r.SetPathParam("id4n", o.ID4N); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Owner != nil {

		// query param owner
		var qrOwner string
		if o.Owner != nil {
			qrOwner = *o.Owner
		}
		qOwner := qrOwner
		if qOwner != "" {
			if err := r.SetQueryParam("owner", qOwner); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
