// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListDocumentsParams creates a new ListDocumentsParams object
// with the default values initialized.
func NewListDocumentsParams() *ListDocumentsParams {
	var ()
	return &ListDocumentsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListDocumentsParamsWithTimeout creates a new ListDocumentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListDocumentsParamsWithTimeout(timeout time.Duration) *ListDocumentsParams {
	var ()
	return &ListDocumentsParams{

		timeout: timeout,
	}
}

// NewListDocumentsParamsWithContext creates a new ListDocumentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListDocumentsParamsWithContext(ctx context.Context) *ListDocumentsParams {
	var ()
	return &ListDocumentsParams{

		Context: ctx,
	}
}

// NewListDocumentsParamsWithHTTPClient creates a new ListDocumentsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListDocumentsParamsWithHTTPClient(client *http.Client) *ListDocumentsParams {
	var ()
	return &ListDocumentsParams{
		HTTPClient: client,
	}
}

/*ListDocumentsParams contains all the parameters to send to the API endpoint
for the list documents operation typically these are written to a http.Request
*/
type ListDocumentsParams struct {

	/*ID4N
	  id4n

	*/
	ID4N string
	/*Limit
	  The maximum count of returned elements

	*/
	Limit *int32
	/*Offset
	  Start with the n-th element

	*/
	Offset *int32
	/*OrganizationID
	  organizationId

	*/
	OrganizationID string
	/*Owner
	  Filter by owner organization

	*/
	Owner *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list documents params
func (o *ListDocumentsParams) WithTimeout(timeout time.Duration) *ListDocumentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list documents params
func (o *ListDocumentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list documents params
func (o *ListDocumentsParams) WithContext(ctx context.Context) *ListDocumentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list documents params
func (o *ListDocumentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list documents params
func (o *ListDocumentsParams) WithHTTPClient(client *http.Client) *ListDocumentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list documents params
func (o *ListDocumentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID4N adds the id4n to the list documents params
func (o *ListDocumentsParams) WithID4N(id4n string) *ListDocumentsParams {
	o.SetID4N(id4n)
	return o
}

// SetID4N adds the id4n to the list documents params
func (o *ListDocumentsParams) SetID4N(id4n string) {
	o.ID4N = id4n
}

// WithLimit adds the limit to the list documents params
func (o *ListDocumentsParams) WithLimit(limit *int32) *ListDocumentsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list documents params
func (o *ListDocumentsParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithOffset adds the offset to the list documents params
func (o *ListDocumentsParams) WithOffset(offset *int32) *ListDocumentsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the list documents params
func (o *ListDocumentsParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WithOrganizationID adds the organizationID to the list documents params
func (o *ListDocumentsParams) WithOrganizationID(organizationID string) *ListDocumentsParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the list documents params
func (o *ListDocumentsParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WithOwner adds the owner to the list documents params
func (o *ListDocumentsParams) WithOwner(owner *string) *ListDocumentsParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the list documents params
func (o *ListDocumentsParams) SetOwner(owner *string) {
	o.Owner = owner
}

// WriteToRequest writes these params to a swagger request
func (o *ListDocumentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id4n
	if err := r.SetPathParam("id4n", o.ID4N); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	if o.Owner != nil {

		// query param owner
		var qrOwner string
		if o.Owner != nil {
			qrOwner = *o.Owner
		}
		qOwner := qrOwner
		if qOwner != "" {
			if err := r.SetQueryParam("owner", qOwner); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
