// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGETAllOrganizationRolesParams creates a new GETAllOrganizationRolesParams object
// with the default values initialized.
func NewGETAllOrganizationRolesParams() *GETAllOrganizationRolesParams {
	var ()
	return &GETAllOrganizationRolesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGETAllOrganizationRolesParamsWithTimeout creates a new GETAllOrganizationRolesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGETAllOrganizationRolesParamsWithTimeout(timeout time.Duration) *GETAllOrganizationRolesParams {
	var ()
	return &GETAllOrganizationRolesParams{

		timeout: timeout,
	}
}

// NewGETAllOrganizationRolesParamsWithContext creates a new GETAllOrganizationRolesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGETAllOrganizationRolesParamsWithContext(ctx context.Context) *GETAllOrganizationRolesParams {
	var ()
	return &GETAllOrganizationRolesParams{

		Context: ctx,
	}
}

// NewGETAllOrganizationRolesParamsWithHTTPClient creates a new GETAllOrganizationRolesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGETAllOrganizationRolesParamsWithHTTPClient(client *http.Client) *GETAllOrganizationRolesParams {
	var ()
	return &GETAllOrganizationRolesParams{
		HTTPClient: client,
	}
}

/*GETAllOrganizationRolesParams contains all the parameters to send to the API endpoint
for the get all organization roles operation typically these are written to a http.Request
*/
type GETAllOrganizationRolesParams struct {

	/*Limit
	  The maximum count of returned elements

	*/
	Limit *int32
	/*Offset
	  Start with the n-th element

	*/
	Offset *int32
	/*OrganizationID
	  organizationId

	*/
	OrganizationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all organization roles params
func (o *GETAllOrganizationRolesParams) WithTimeout(timeout time.Duration) *GETAllOrganizationRolesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all organization roles params
func (o *GETAllOrganizationRolesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all organization roles params
func (o *GETAllOrganizationRolesParams) WithContext(ctx context.Context) *GETAllOrganizationRolesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all organization roles params
func (o *GETAllOrganizationRolesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all organization roles params
func (o *GETAllOrganizationRolesParams) WithHTTPClient(client *http.Client) *GETAllOrganizationRolesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all organization roles params
func (o *GETAllOrganizationRolesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get all organization roles params
func (o *GETAllOrganizationRolesParams) WithLimit(limit *int32) *GETAllOrganizationRolesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get all organization roles params
func (o *GETAllOrganizationRolesParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithOffset adds the offset to the get all organization roles params
func (o *GETAllOrganizationRolesParams) WithOffset(offset *int32) *GETAllOrganizationRolesParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get all organization roles params
func (o *GETAllOrganizationRolesParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WithOrganizationID adds the organizationID to the get all organization roles params
func (o *GETAllOrganizationRolesParams) WithOrganizationID(organizationID string) *GETAllOrganizationRolesParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the get all organization roles params
func (o *GETAllOrganizationRolesParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WriteToRequest writes these params to a swagger request
func (o *GETAllOrganizationRolesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
