// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGETUserRolesParams creates a new GETUserRolesParams object
// with the default values initialized.
func NewGETUserRolesParams() *GETUserRolesParams {
	var ()
	return &GETUserRolesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGETUserRolesParamsWithTimeout creates a new GETUserRolesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGETUserRolesParamsWithTimeout(timeout time.Duration) *GETUserRolesParams {
	var ()
	return &GETUserRolesParams{

		timeout: timeout,
	}
}

// NewGETUserRolesParamsWithContext creates a new GETUserRolesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGETUserRolesParamsWithContext(ctx context.Context) *GETUserRolesParams {
	var ()
	return &GETUserRolesParams{

		Context: ctx,
	}
}

// NewGETUserRolesParamsWithHTTPClient creates a new GETUserRolesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGETUserRolesParamsWithHTTPClient(client *http.Client) *GETUserRolesParams {
	var ()
	return &GETUserRolesParams{
		HTTPClient: client,
	}
}

/*GETUserRolesParams contains all the parameters to send to the API endpoint
for the get user roles operation typically these are written to a http.Request
*/
type GETUserRolesParams struct {

	/*Limit
	  The maximum count of returned elements

	*/
	Limit *int32
	/*Offset
	  Start with the n-th element

	*/
	Offset *int32
	/*OrganizationID
	  The namespace of the organization

	*/
	OrganizationID string
	/*Username
	  username

	*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get user roles params
func (o *GETUserRolesParams) WithTimeout(timeout time.Duration) *GETUserRolesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user roles params
func (o *GETUserRolesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user roles params
func (o *GETUserRolesParams) WithContext(ctx context.Context) *GETUserRolesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user roles params
func (o *GETUserRolesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user roles params
func (o *GETUserRolesParams) WithHTTPClient(client *http.Client) *GETUserRolesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user roles params
func (o *GETUserRolesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get user roles params
func (o *GETUserRolesParams) WithLimit(limit *int32) *GETUserRolesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get user roles params
func (o *GETUserRolesParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithOffset adds the offset to the get user roles params
func (o *GETUserRolesParams) WithOffset(offset *int32) *GETUserRolesParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get user roles params
func (o *GETUserRolesParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WithOrganizationID adds the organizationID to the get user roles params
func (o *GETUserRolesParams) WithOrganizationID(organizationID string) *GETUserRolesParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the get user roles params
func (o *GETUserRolesParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WithUsername adds the username to the get user roles params
func (o *GETUserRolesParams) WithUsername(username string) *GETUserRolesParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the get user roles params
func (o *GETUserRolesParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *GETUserRolesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
