// Code generated by go-swagger; DO NOT EDIT.

package alias

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSearchByAliasParams creates a new SearchByAliasParams object
// with the default values initialized.
func NewSearchByAliasParams() *SearchByAliasParams {
	var ()
	return &SearchByAliasParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSearchByAliasParamsWithTimeout creates a new SearchByAliasParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSearchByAliasParamsWithTimeout(timeout time.Duration) *SearchByAliasParams {
	var ()
	return &SearchByAliasParams{

		timeout: timeout,
	}
}

// NewSearchByAliasParamsWithContext creates a new SearchByAliasParams object
// with the default values initialized, and the ability to set a context for a request
func NewSearchByAliasParamsWithContext(ctx context.Context) *SearchByAliasParams {
	var ()
	return &SearchByAliasParams{

		Context: ctx,
	}
}

// NewSearchByAliasParamsWithHTTPClient creates a new SearchByAliasParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSearchByAliasParamsWithHTTPClient(client *http.Client) *SearchByAliasParams {
	var ()
	return &SearchByAliasParams{
		HTTPClient: client,
	}
}

/*SearchByAliasParams contains all the parameters to send to the API endpoint
for the search by alias operation typically these are written to a http.Request
*/
type SearchByAliasParams struct {

	/*Alias
	  The alias to search for

	*/
	Alias string
	/*AliasType
	  Alias type type to search for

	*/
	AliasType string
	/*Limit
	  The maximum count of returned elements

	*/
	Limit *int32
	/*Offset
	  Start with the n-th element

	*/
	Offset *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the search by alias params
func (o *SearchByAliasParams) WithTimeout(timeout time.Duration) *SearchByAliasParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search by alias params
func (o *SearchByAliasParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search by alias params
func (o *SearchByAliasParams) WithContext(ctx context.Context) *SearchByAliasParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search by alias params
func (o *SearchByAliasParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search by alias params
func (o *SearchByAliasParams) WithHTTPClient(client *http.Client) *SearchByAliasParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search by alias params
func (o *SearchByAliasParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAlias adds the alias to the search by alias params
func (o *SearchByAliasParams) WithAlias(alias string) *SearchByAliasParams {
	o.SetAlias(alias)
	return o
}

// SetAlias adds the alias to the search by alias params
func (o *SearchByAliasParams) SetAlias(alias string) {
	o.Alias = alias
}

// WithAliasType adds the aliasType to the search by alias params
func (o *SearchByAliasParams) WithAliasType(aliasType string) *SearchByAliasParams {
	o.SetAliasType(aliasType)
	return o
}

// SetAliasType adds the aliasType to the search by alias params
func (o *SearchByAliasParams) SetAliasType(aliasType string) {
	o.AliasType = aliasType
}

// WithLimit adds the limit to the search by alias params
func (o *SearchByAliasParams) WithLimit(limit *int32) *SearchByAliasParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the search by alias params
func (o *SearchByAliasParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithOffset adds the offset to the search by alias params
func (o *SearchByAliasParams) WithOffset(offset *int32) *SearchByAliasParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the search by alias params
func (o *SearchByAliasParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *SearchByAliasParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param alias
	qrAlias := o.Alias
	qAlias := qrAlias
	if qAlias != "" {
		if err := r.SetQueryParam("alias", qAlias); err != nil {
			return err
		}
	}

	// query param aliasType
	qrAliasType := o.AliasType
	qAliasType := qrAliasType
	if qAliasType != "" {
		if err := r.SetQueryParam("aliasType", qAliasType); err != nil {
			return err
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
