// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListElementsOfCollectionParams creates a new ListElementsOfCollectionParams object
// with the default values initialized.
func NewListElementsOfCollectionParams() *ListElementsOfCollectionParams {
	var ()
	return &ListElementsOfCollectionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListElementsOfCollectionParamsWithTimeout creates a new ListElementsOfCollectionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListElementsOfCollectionParamsWithTimeout(timeout time.Duration) *ListElementsOfCollectionParams {
	var ()
	return &ListElementsOfCollectionParams{

		timeout: timeout,
	}
}

// NewListElementsOfCollectionParamsWithContext creates a new ListElementsOfCollectionParams object
// with the default values initialized, and the ability to set a context for a request
func NewListElementsOfCollectionParamsWithContext(ctx context.Context) *ListElementsOfCollectionParams {
	var ()
	return &ListElementsOfCollectionParams{

		Context: ctx,
	}
}

// NewListElementsOfCollectionParamsWithHTTPClient creates a new ListElementsOfCollectionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListElementsOfCollectionParamsWithHTTPClient(client *http.Client) *ListElementsOfCollectionParams {
	var ()
	return &ListElementsOfCollectionParams{
		HTTPClient: client,
	}
}

/*ListElementsOfCollectionParams contains all the parameters to send to the API endpoint
for the list elements of collection operation typically these are written to a http.Request
*/
type ListElementsOfCollectionParams struct {

	/*ID4N
	  id4n

	*/
	ID4N string
	/*Limit
	  The maximum count of returned elements

	*/
	Limit *int32
	/*Offset
	  Start with the n-th element

	*/
	Offset *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list elements of collection params
func (o *ListElementsOfCollectionParams) WithTimeout(timeout time.Duration) *ListElementsOfCollectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list elements of collection params
func (o *ListElementsOfCollectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list elements of collection params
func (o *ListElementsOfCollectionParams) WithContext(ctx context.Context) *ListElementsOfCollectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list elements of collection params
func (o *ListElementsOfCollectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list elements of collection params
func (o *ListElementsOfCollectionParams) WithHTTPClient(client *http.Client) *ListElementsOfCollectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list elements of collection params
func (o *ListElementsOfCollectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID4N adds the id4n to the list elements of collection params
func (o *ListElementsOfCollectionParams) WithID4N(id4n string) *ListElementsOfCollectionParams {
	o.SetID4N(id4n)
	return o
}

// SetID4N adds the id4n to the list elements of collection params
func (o *ListElementsOfCollectionParams) SetID4N(id4n string) {
	o.ID4N = id4n
}

// WithLimit adds the limit to the list elements of collection params
func (o *ListElementsOfCollectionParams) WithLimit(limit *int32) *ListElementsOfCollectionParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list elements of collection params
func (o *ListElementsOfCollectionParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithOffset adds the offset to the list elements of collection params
func (o *ListElementsOfCollectionParams) WithOffset(offset *int32) *ListElementsOfCollectionParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the list elements of collection params
func (o *ListElementsOfCollectionParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *ListElementsOfCollectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id4n
	if err := r.SetPathParam("id4n", o.ID4N); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
