// Code generated by go-swagger; DO NOT EDIT.

package history

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	api_models "github.com/BlueRainSoftware/id4i-cli/api_models"
)

// NewUpdateItemParams creates a new UpdateItemParams object
// with the default values initialized.
func NewUpdateItemParams() *UpdateItemParams {
	var ()
	return &UpdateItemParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateItemParamsWithTimeout creates a new UpdateItemParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateItemParamsWithTimeout(timeout time.Duration) *UpdateItemParams {
	var ()
	return &UpdateItemParams{

		timeout: timeout,
	}
}

// NewUpdateItemParamsWithContext creates a new UpdateItemParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateItemParamsWithContext(ctx context.Context) *UpdateItemParams {
	var ()
	return &UpdateItemParams{

		Context: ctx,
	}
}

// NewUpdateItemParamsWithHTTPClient creates a new UpdateItemParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateItemParamsWithHTTPClient(client *http.Client) *UpdateItemParams {
	var ()
	return &UpdateItemParams{
		HTTPClient: client,
	}
}

/*UpdateItemParams contains all the parameters to send to the API endpoint
for the update item operation typically these are written to a http.Request
*/
type UpdateItemParams struct {

	/*ID4N
	  GUID to retrieve the history for

	*/
	ID4N string
	/*OrganizationID
	  organizationId

	*/
	OrganizationID string
	/*SequenceID
	  sequenceId

	*/
	SequenceID int32
	/*Update
	  update

	*/
	Update *api_models.HistoryItemUpdate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update item params
func (o *UpdateItemParams) WithTimeout(timeout time.Duration) *UpdateItemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update item params
func (o *UpdateItemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update item params
func (o *UpdateItemParams) WithContext(ctx context.Context) *UpdateItemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update item params
func (o *UpdateItemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update item params
func (o *UpdateItemParams) WithHTTPClient(client *http.Client) *UpdateItemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update item params
func (o *UpdateItemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID4N adds the id4n to the update item params
func (o *UpdateItemParams) WithID4N(id4n string) *UpdateItemParams {
	o.SetID4N(id4n)
	return o
}

// SetID4N adds the id4n to the update item params
func (o *UpdateItemParams) SetID4N(id4n string) {
	o.ID4N = id4n
}

// WithOrganizationID adds the organizationID to the update item params
func (o *UpdateItemParams) WithOrganizationID(organizationID string) *UpdateItemParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the update item params
func (o *UpdateItemParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WithSequenceID adds the sequenceID to the update item params
func (o *UpdateItemParams) WithSequenceID(sequenceID int32) *UpdateItemParams {
	o.SetSequenceID(sequenceID)
	return o
}

// SetSequenceID adds the sequenceId to the update item params
func (o *UpdateItemParams) SetSequenceID(sequenceID int32) {
	o.SequenceID = sequenceID
}

// WithUpdate adds the update to the update item params
func (o *UpdateItemParams) WithUpdate(update *api_models.HistoryItemUpdate) *UpdateItemParams {
	o.SetUpdate(update)
	return o
}

// SetUpdate adds the update to the update item params
func (o *UpdateItemParams) SetUpdate(update *api_models.HistoryItemUpdate) {
	o.Update = update
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateItemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id4n
	if err := r.SetPathParam("id4n", o.ID4N); err != nil {
		return err
	}

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	// path param sequenceId
	if err := r.SetPathParam("sequenceId", swag.FormatInt32(o.SequenceID)); err != nil {
		return err
	}

	if o.Update != nil {
		if err := r.SetBodyParam(o.Update); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
