// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFindCollectionParams creates a new FindCollectionParams object
// with the default values initialized.
func NewFindCollectionParams() *FindCollectionParams {
	var ()
	return &FindCollectionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFindCollectionParamsWithTimeout creates a new FindCollectionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFindCollectionParamsWithTimeout(timeout time.Duration) *FindCollectionParams {
	var ()
	return &FindCollectionParams{

		timeout: timeout,
	}
}

// NewFindCollectionParamsWithContext creates a new FindCollectionParams object
// with the default values initialized, and the ability to set a context for a request
func NewFindCollectionParamsWithContext(ctx context.Context) *FindCollectionParams {
	var ()
	return &FindCollectionParams{

		Context: ctx,
	}
}

// NewFindCollectionParamsWithHTTPClient creates a new FindCollectionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFindCollectionParamsWithHTTPClient(client *http.Client) *FindCollectionParams {
	var ()
	return &FindCollectionParams{
		HTTPClient: client,
	}
}

/*FindCollectionParams contains all the parameters to send to the API endpoint
for the find collection operation typically these are written to a http.Request
*/
type FindCollectionParams struct {

	/*ID4N
	  id4n

	*/
	ID4N string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the find collection params
func (o *FindCollectionParams) WithTimeout(timeout time.Duration) *FindCollectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find collection params
func (o *FindCollectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find collection params
func (o *FindCollectionParams) WithContext(ctx context.Context) *FindCollectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find collection params
func (o *FindCollectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find collection params
func (o *FindCollectionParams) WithHTTPClient(client *http.Client) *FindCollectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find collection params
func (o *FindCollectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID4N adds the id4n to the find collection params
func (o *FindCollectionParams) WithID4N(id4n string) *FindCollectionParams {
	o.SetID4N(id4n)
	return o
}

// SetID4N adds the id4n to the find collection params
func (o *FindCollectionParams) SetID4N(id4n string) {
	o.ID4N = id4n
}

// WriteToRequest writes these params to a swagger request
func (o *FindCollectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id4n
	if err := r.SetPathParam("id4n", o.ID4N); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
