// Code generated by go-swagger; DO NOT EDIT.

package auditing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new auditing API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for auditing API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
ListOrganizationChangeLog lists change log entries of an organization

Listing change log entries of the specified organization id.
*/
func (a *Client) ListOrganizationChangeLog(params *ListOrganizationChangeLogParams, authInfo runtime.ClientAuthInfoWriter) (*ListOrganizationChangeLogOK, *ListOrganizationChangeLogAccepted, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListOrganizationChangeLogParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "listOrganizationChangeLog",
		Method:             "GET",
		PathPattern:        "/api/v1/changelog/organization/{organizationId}/",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json", "application/xml"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ListOrganizationChangeLogReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, err
	}
	switch value := result.(type) {
	case *ListOrganizationChangeLogOK:
		return value, nil, nil
	case *ListOrganizationChangeLogAccepted:
		return nil, value, nil
	}
	return nil, nil, nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
