// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFindOrganizationAddressParams creates a new FindOrganizationAddressParams object
// with the default values initialized.
func NewFindOrganizationAddressParams() *FindOrganizationAddressParams {
	var ()
	return &FindOrganizationAddressParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFindOrganizationAddressParamsWithTimeout creates a new FindOrganizationAddressParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFindOrganizationAddressParamsWithTimeout(timeout time.Duration) *FindOrganizationAddressParams {
	var ()
	return &FindOrganizationAddressParams{

		timeout: timeout,
	}
}

// NewFindOrganizationAddressParamsWithContext creates a new FindOrganizationAddressParams object
// with the default values initialized, and the ability to set a context for a request
func NewFindOrganizationAddressParamsWithContext(ctx context.Context) *FindOrganizationAddressParams {
	var ()
	return &FindOrganizationAddressParams{

		Context: ctx,
	}
}

// NewFindOrganizationAddressParamsWithHTTPClient creates a new FindOrganizationAddressParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFindOrganizationAddressParamsWithHTTPClient(client *http.Client) *FindOrganizationAddressParams {
	var ()
	return &FindOrganizationAddressParams{
		HTTPClient: client,
	}
}

/*FindOrganizationAddressParams contains all the parameters to send to the API endpoint
for the find organization address operation typically these are written to a http.Request
*/
type FindOrganizationAddressParams struct {

	/*OrganizationID
	  organizationId

	*/
	OrganizationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the find organization address params
func (o *FindOrganizationAddressParams) WithTimeout(timeout time.Duration) *FindOrganizationAddressParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find organization address params
func (o *FindOrganizationAddressParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find organization address params
func (o *FindOrganizationAddressParams) WithContext(ctx context.Context) *FindOrganizationAddressParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find organization address params
func (o *FindOrganizationAddressParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find organization address params
func (o *FindOrganizationAddressParams) WithHTTPClient(client *http.Client) *FindOrganizationAddressParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find organization address params
func (o *FindOrganizationAddressParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganizationID adds the organizationID to the find organization address params
func (o *FindOrganizationAddressParams) WithOrganizationID(organizationID string) *FindOrganizationAddressParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the find organization address params
func (o *FindOrganizationAddressParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WriteToRequest writes these params to a swagger request
func (o *FindOrganizationAddressParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
