// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	api_models "github.com/BlueRainSoftware/id4i-cli/api/models"
)

// NewAddGUIDAliasParams creates a new AddGUIDAliasParams object
// with the default values initialized.
func NewAddGUIDAliasParams() *AddGUIDAliasParams {
	var ()
	return &AddGUIDAliasParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddGUIDAliasParamsWithTimeout creates a new AddGUIDAliasParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddGUIDAliasParamsWithTimeout(timeout time.Duration) *AddGUIDAliasParams {
	var ()
	return &AddGUIDAliasParams{

		timeout: timeout,
	}
}

// NewAddGUIDAliasParamsWithContext creates a new AddGUIDAliasParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddGUIDAliasParamsWithContext(ctx context.Context) *AddGUIDAliasParams {
	var ()
	return &AddGUIDAliasParams{

		Context: ctx,
	}
}

// NewAddGUIDAliasParamsWithHTTPClient creates a new AddGUIDAliasParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddGUIDAliasParamsWithHTTPClient(client *http.Client) *AddGUIDAliasParams {
	var ()
	return &AddGUIDAliasParams{
		HTTPClient: client,
	}
}

/*AddGUIDAliasParams contains all the parameters to send to the API endpoint
for the add Guid alias operation typically these are written to a http.Request
*/
type AddGUIDAliasParams struct {

	/*Alias
	  The alias to add or update

	*/
	Alias *api_models.GUIDAlias
	/*AliasType
	  Alias type, see the corresponding API model

	*/
	AliasType string
	/*ID4N
	  The GUID or Collection to operate on

	*/
	ID4N string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add Guid alias params
func (o *AddGUIDAliasParams) WithTimeout(timeout time.Duration) *AddGUIDAliasParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add Guid alias params
func (o *AddGUIDAliasParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add Guid alias params
func (o *AddGUIDAliasParams) WithContext(ctx context.Context) *AddGUIDAliasParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add Guid alias params
func (o *AddGUIDAliasParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add Guid alias params
func (o *AddGUIDAliasParams) WithHTTPClient(client *http.Client) *AddGUIDAliasParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add Guid alias params
func (o *AddGUIDAliasParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAlias adds the alias to the add Guid alias params
func (o *AddGUIDAliasParams) WithAlias(alias *api_models.GUIDAlias) *AddGUIDAliasParams {
	o.SetAlias(alias)
	return o
}

// SetAlias adds the alias to the add Guid alias params
func (o *AddGUIDAliasParams) SetAlias(alias *api_models.GUIDAlias) {
	o.Alias = alias
}

// WithAliasType adds the aliasType to the add Guid alias params
func (o *AddGUIDAliasParams) WithAliasType(aliasType string) *AddGUIDAliasParams {
	o.SetAliasType(aliasType)
	return o
}

// SetAliasType adds the aliasType to the add Guid alias params
func (o *AddGUIDAliasParams) SetAliasType(aliasType string) {
	o.AliasType = aliasType
}

// WithID4N adds the id4n to the add Guid alias params
func (o *AddGUIDAliasParams) WithID4N(id4n string) *AddGUIDAliasParams {
	o.SetID4N(id4n)
	return o
}

// SetID4N adds the id4n to the add Guid alias params
func (o *AddGUIDAliasParams) SetID4N(id4n string) {
	o.ID4N = id4n
}

// WriteToRequest writes these params to a swagger request
func (o *AddGUIDAliasParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Alias != nil {
		if err := r.SetBodyParam(o.Alias); err != nil {
			return err
		}
	}

	// path param aliasType
	if err := r.SetPathParam("aliasType", o.AliasType); err != nil {
		return err
	}

	// path param id4n
	if err := r.SetPathParam("id4n", o.ID4N); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
