// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewResolveImageUsingGETParams creates a new ResolveImageUsingGETParams object
// with the default values initialized.
func NewResolveImageUsingGETParams() *ResolveImageUsingGETParams {
	var ()
	return &ResolveImageUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewResolveImageUsingGETParamsWithTimeout creates a new ResolveImageUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewResolveImageUsingGETParamsWithTimeout(timeout time.Duration) *ResolveImageUsingGETParams {
	var ()
	return &ResolveImageUsingGETParams{

		timeout: timeout,
	}
}

// NewResolveImageUsingGETParamsWithContext creates a new ResolveImageUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewResolveImageUsingGETParamsWithContext(ctx context.Context) *ResolveImageUsingGETParams {
	var ()
	return &ResolveImageUsingGETParams{

		Context: ctx,
	}
}

// NewResolveImageUsingGETParamsWithHTTPClient creates a new ResolveImageUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewResolveImageUsingGETParamsWithHTTPClient(client *http.Client) *ResolveImageUsingGETParams {
	var ()
	return &ResolveImageUsingGETParams{
		HTTPClient: client,
	}
}

/*ResolveImageUsingGETParams contains all the parameters to send to the API endpoint
for the resolve image using GET operation typically these are written to a http.Request
*/
type ResolveImageUsingGETParams struct {

	/*ImageID
	  The id of the image to be resolved.

	*/
	ImageID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the resolve image using GET params
func (o *ResolveImageUsingGETParams) WithTimeout(timeout time.Duration) *ResolveImageUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the resolve image using GET params
func (o *ResolveImageUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the resolve image using GET params
func (o *ResolveImageUsingGETParams) WithContext(ctx context.Context) *ResolveImageUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the resolve image using GET params
func (o *ResolveImageUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the resolve image using GET params
func (o *ResolveImageUsingGETParams) WithHTTPClient(client *http.Client) *ResolveImageUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the resolve image using GET params
func (o *ResolveImageUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImageID adds the imageID to the resolve image using GET params
func (o *ResolveImageUsingGETParams) WithImageID(imageID string) *ResolveImageUsingGETParams {
	o.SetImageID(imageID)
	return o
}

// SetImageID adds the imageId to the resolve image using GET params
func (o *ResolveImageUsingGETParams) SetImageID(imageID string) {
	o.ImageID = imageID
}

// WriteToRequest writes these params to a swagger request
func (o *ResolveImageUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param imageID
	if err := r.SetPathParam("imageID", o.ImageID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
