// Code generated by go-swagger; DO NOT EDIT.

package api_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIKeyPrivilegeInfo ApiKeyPrivilegeInfo
// swagger:model ApiKeyPrivilegeInfo
type APIKeyPrivilegeInfo struct {

	// allows billable operations
	AllowsBillableOperations bool `json:"allowsBillableOperations,omitempty"`

	// help text
	HelpText string `json:"helpText,omitempty"`

	// id4n associated
	// Required: true
	ID4NAssociated *bool `json:"id4nAssociated"`

	// name
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this Api key privilege info
func (m *APIKeyPrivilegeInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID4NAssociated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIKeyPrivilegeInfo) validateID4NAssociated(formats strfmt.Registry) error {

	if err := validate.Required("id4nAssociated", "body", m.ID4NAssociated); err != nil {
		return err
	}

	return nil
}

func (m *APIKeyPrivilegeInfo) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIKeyPrivilegeInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIKeyPrivilegeInfo) UnmarshalBinary(b []byte) error {
	var res APIKeyPrivilegeInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
