// Code generated by go-swagger; DO NOT EDIT.

package api_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIKeyPrivilege ApiKeyPrivilege
// swagger:model ApiKeyPrivilege
type APIKeyPrivilege struct {

	// id4n associated
	// Required: true
	ID4NAssociated *bool `json:"id4nAssociated"`

	// privilege
	// Required: true
	Privilege *string `json:"privilege"`
}

// Validate validates this Api key privilege
func (m *APIKeyPrivilege) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID4NAssociated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrivilege(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIKeyPrivilege) validateID4NAssociated(formats strfmt.Registry) error {

	if err := validate.Required("id4nAssociated", "body", m.ID4NAssociated); err != nil {
		return err
	}

	return nil
}

func (m *APIKeyPrivilege) validatePrivilege(formats strfmt.Registry) error {

	if err := validate.Required("privilege", "body", m.Privilege); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIKeyPrivilege) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIKeyPrivilege) UnmarshalBinary(b []byte) error {
	var res APIKeyPrivilege
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
