// Code generated by go-swagger; DO NOT EDIT.

package api_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrganizationUserInvitationListRequest OrganizationUserInvitationListRequest
// swagger:model OrganizationUserInvitationListRequest
type OrganizationUserInvitationListRequest struct {

	// invitations
	// Required: true
	Invitations []*OrganizationUserInvitation `json:"invitations"`
}

// Validate validates this organization user invitation list request
func (m *OrganizationUserInvitationListRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInvitations(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrganizationUserInvitationListRequest) validateInvitations(formats strfmt.Registry) error {

	if err := validate.Required("invitations", "body", m.Invitations); err != nil {
		return err
	}

	for i := 0; i < len(m.Invitations); i++ {
		if swag.IsZero(m.Invitations[i]) { // not required
			continue
		}

		if m.Invitations[i] != nil {
			if err := m.Invitations[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("invitations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrganizationUserInvitationListRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrganizationUserInvitationListRequest) UnmarshalBinary(b []byte) error {
	var res OrganizationUserInvitationListRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
