// Code generated by go-swagger; DO NOT EDIT.

package api_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// AppInfoPresentation AppInfoPresentation
// swagger:model AppInfoPresentation
type AppInfoPresentation struct {

	// branch
	Branch string `json:"branch,omitempty"`

	// commit time
	CommitTime string `json:"commitTime,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// production mode
	ProductionMode bool `json:"productionMode,omitempty"`

	// revision
	Revision string `json:"revision,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this app info presentation
func (m *AppInfoPresentation) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AppInfoPresentation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppInfoPresentation) UnmarshalBinary(b []byte) error {
	var res AppInfoPresentation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
