// Code generated by go-swagger; DO NOT EDIT.

package alias

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGETGUIDAliasTypesParams creates a new GETGUIDAliasTypesParams object
// with the default values initialized.
func NewGETGUIDAliasTypesParams() *GETGUIDAliasTypesParams {

	return &GETGUIDAliasTypesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGETGUIDAliasTypesParamsWithTimeout creates a new GETGUIDAliasTypesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGETGUIDAliasTypesParamsWithTimeout(timeout time.Duration) *GETGUIDAliasTypesParams {

	return &GETGUIDAliasTypesParams{

		timeout: timeout,
	}
}

// NewGETGUIDAliasTypesParamsWithContext creates a new GETGUIDAliasTypesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGETGUIDAliasTypesParamsWithContext(ctx context.Context) *GETGUIDAliasTypesParams {

	return &GETGUIDAliasTypesParams{

		Context: ctx,
	}
}

// NewGETGUIDAliasTypesParamsWithHTTPClient creates a new GETGUIDAliasTypesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGETGUIDAliasTypesParamsWithHTTPClient(client *http.Client) *GETGUIDAliasTypesParams {

	return &GETGUIDAliasTypesParams{
		HTTPClient: client,
	}
}

/*GETGUIDAliasTypesParams contains all the parameters to send to the API endpoint
for the get Guid alias types operation typically these are written to a http.Request
*/
type GETGUIDAliasTypesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get Guid alias types params
func (o *GETGUIDAliasTypesParams) WithTimeout(timeout time.Duration) *GETGUIDAliasTypesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get Guid alias types params
func (o *GETGUIDAliasTypesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get Guid alias types params
func (o *GETGUIDAliasTypesParams) WithContext(ctx context.Context) *GETGUIDAliasTypesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get Guid alias types params
func (o *GETGUIDAliasTypesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get Guid alias types params
func (o *GETGUIDAliasTypesParams) WithHTTPClient(client *http.Client) *GETGUIDAliasTypesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get Guid alias types params
func (o *GETGUIDAliasTypesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GETGUIDAliasTypesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
