// Code generated by go-swagger; DO NOT EDIT.

package api_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	api_models "github.com/BlueRainSoftware/id4i-cli/api_models"
)

// ListAllAPIKeysOfOrganizationReader is a Reader for the ListAllAPIKeysOfOrganization structure.
type ListAllAPIKeysOfOrganizationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAllAPIKeysOfOrganizationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListAllAPIKeysOfOrganizationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 202:
		result := NewListAllAPIKeysOfOrganizationAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewListAllAPIKeysOfOrganizationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewListAllAPIKeysOfOrganizationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewListAllAPIKeysOfOrganizationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 405:
		result := NewListAllAPIKeysOfOrganizationMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 406:
		result := NewListAllAPIKeysOfOrganizationNotAcceptable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 415:
		result := NewListAllAPIKeysOfOrganizationUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewListAllAPIKeysOfOrganizationInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListAllAPIKeysOfOrganizationOK creates a ListAllAPIKeysOfOrganizationOK with default headers values
func NewListAllAPIKeysOfOrganizationOK() *ListAllAPIKeysOfOrganizationOK {
	return &ListAllAPIKeysOfOrganizationOK{}
}

/*ListAllAPIKeysOfOrganizationOK handles this case with default header values.

OK
*/
type ListAllAPIKeysOfOrganizationOK struct {
	Payload *api_models.PaginatedAPIKeyResponse
}

func (o *ListAllAPIKeysOfOrganizationOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/apikeys][%d] listAllApiKeysOfOrganizationOK  %+v", 200, o.Payload)
}

func (o *ListAllAPIKeysOfOrganizationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.PaginatedAPIKeyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAllAPIKeysOfOrganizationAccepted creates a ListAllAPIKeysOfOrganizationAccepted with default headers values
func NewListAllAPIKeysOfOrganizationAccepted() *ListAllAPIKeysOfOrganizationAccepted {
	return &ListAllAPIKeysOfOrganizationAccepted{}
}

/*ListAllAPIKeysOfOrganizationAccepted handles this case with default header values.

Accepted
*/
type ListAllAPIKeysOfOrganizationAccepted struct {
}

func (o *ListAllAPIKeysOfOrganizationAccepted) Error() string {
	return fmt.Sprintf("[GET /api/v1/apikeys][%d] listAllApiKeysOfOrganizationAccepted ", 202)
}

func (o *ListAllAPIKeysOfOrganizationAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListAllAPIKeysOfOrganizationUnauthorized creates a ListAllAPIKeysOfOrganizationUnauthorized with default headers values
func NewListAllAPIKeysOfOrganizationUnauthorized() *ListAllAPIKeysOfOrganizationUnauthorized {
	return &ListAllAPIKeysOfOrganizationUnauthorized{}
}

/*ListAllAPIKeysOfOrganizationUnauthorized handles this case with default header values.

Unauthorized
*/
type ListAllAPIKeysOfOrganizationUnauthorized struct {
	Payload *api_models.APIError
}

func (o *ListAllAPIKeysOfOrganizationUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1/apikeys][%d] listAllApiKeysOfOrganizationUnauthorized  %+v", 401, o.Payload)
}

func (o *ListAllAPIKeysOfOrganizationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAllAPIKeysOfOrganizationForbidden creates a ListAllAPIKeysOfOrganizationForbidden with default headers values
func NewListAllAPIKeysOfOrganizationForbidden() *ListAllAPIKeysOfOrganizationForbidden {
	return &ListAllAPIKeysOfOrganizationForbidden{}
}

/*ListAllAPIKeysOfOrganizationForbidden handles this case with default header values.

Forbidden
*/
type ListAllAPIKeysOfOrganizationForbidden struct {
	Payload *api_models.APIError
}

func (o *ListAllAPIKeysOfOrganizationForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/apikeys][%d] listAllApiKeysOfOrganizationForbidden  %+v", 403, o.Payload)
}

func (o *ListAllAPIKeysOfOrganizationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAllAPIKeysOfOrganizationNotFound creates a ListAllAPIKeysOfOrganizationNotFound with default headers values
func NewListAllAPIKeysOfOrganizationNotFound() *ListAllAPIKeysOfOrganizationNotFound {
	return &ListAllAPIKeysOfOrganizationNotFound{}
}

/*ListAllAPIKeysOfOrganizationNotFound handles this case with default header values.

Not Found
*/
type ListAllAPIKeysOfOrganizationNotFound struct {
	Payload *api_models.APIError
}

func (o *ListAllAPIKeysOfOrganizationNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/apikeys][%d] listAllApiKeysOfOrganizationNotFound  %+v", 404, o.Payload)
}

func (o *ListAllAPIKeysOfOrganizationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAllAPIKeysOfOrganizationMethodNotAllowed creates a ListAllAPIKeysOfOrganizationMethodNotAllowed with default headers values
func NewListAllAPIKeysOfOrganizationMethodNotAllowed() *ListAllAPIKeysOfOrganizationMethodNotAllowed {
	return &ListAllAPIKeysOfOrganizationMethodNotAllowed{}
}

/*ListAllAPIKeysOfOrganizationMethodNotAllowed handles this case with default header values.

Method not allowed
*/
type ListAllAPIKeysOfOrganizationMethodNotAllowed struct {
	Payload *api_models.APIError
}

func (o *ListAllAPIKeysOfOrganizationMethodNotAllowed) Error() string {
	return fmt.Sprintf("[GET /api/v1/apikeys][%d] listAllApiKeysOfOrganizationMethodNotAllowed  %+v", 405, o.Payload)
}

func (o *ListAllAPIKeysOfOrganizationMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAllAPIKeysOfOrganizationNotAcceptable creates a ListAllAPIKeysOfOrganizationNotAcceptable with default headers values
func NewListAllAPIKeysOfOrganizationNotAcceptable() *ListAllAPIKeysOfOrganizationNotAcceptable {
	return &ListAllAPIKeysOfOrganizationNotAcceptable{}
}

/*ListAllAPIKeysOfOrganizationNotAcceptable handles this case with default header values.

Not Acceptable
*/
type ListAllAPIKeysOfOrganizationNotAcceptable struct {
	Payload *api_models.APIError
}

func (o *ListAllAPIKeysOfOrganizationNotAcceptable) Error() string {
	return fmt.Sprintf("[GET /api/v1/apikeys][%d] listAllApiKeysOfOrganizationNotAcceptable  %+v", 406, o.Payload)
}

func (o *ListAllAPIKeysOfOrganizationNotAcceptable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAllAPIKeysOfOrganizationUnsupportedMediaType creates a ListAllAPIKeysOfOrganizationUnsupportedMediaType with default headers values
func NewListAllAPIKeysOfOrganizationUnsupportedMediaType() *ListAllAPIKeysOfOrganizationUnsupportedMediaType {
	return &ListAllAPIKeysOfOrganizationUnsupportedMediaType{}
}

/*ListAllAPIKeysOfOrganizationUnsupportedMediaType handles this case with default header values.

Unsupported Media Type
*/
type ListAllAPIKeysOfOrganizationUnsupportedMediaType struct {
	Payload *api_models.APIError
}

func (o *ListAllAPIKeysOfOrganizationUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[GET /api/v1/apikeys][%d] listAllApiKeysOfOrganizationUnsupportedMediaType  %+v", 415, o.Payload)
}

func (o *ListAllAPIKeysOfOrganizationUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAllAPIKeysOfOrganizationInternalServerError creates a ListAllAPIKeysOfOrganizationInternalServerError with default headers values
func NewListAllAPIKeysOfOrganizationInternalServerError() *ListAllAPIKeysOfOrganizationInternalServerError {
	return &ListAllAPIKeysOfOrganizationInternalServerError{}
}

/*ListAllAPIKeysOfOrganizationInternalServerError handles this case with default header values.

Internal Server Error
*/
type ListAllAPIKeysOfOrganizationInternalServerError struct {
	Payload *api_models.APIError
}

func (o *ListAllAPIKeysOfOrganizationInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/apikeys][%d] listAllApiKeysOfOrganizationInternalServerError  %+v", 500, o.Payload)
}

func (o *ListAllAPIKeysOfOrganizationInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(api_models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
