// Code generated by go-swagger; DO NOT EDIT.

package api_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListAPIKeyPrivilegesParams creates a new ListAPIKeyPrivilegesParams object
// with the default values initialized.
func NewListAPIKeyPrivilegesParams() *ListAPIKeyPrivilegesParams {
	var ()
	return &ListAPIKeyPrivilegesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListAPIKeyPrivilegesParamsWithTimeout creates a new ListAPIKeyPrivilegesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListAPIKeyPrivilegesParamsWithTimeout(timeout time.Duration) *ListAPIKeyPrivilegesParams {
	var ()
	return &ListAPIKeyPrivilegesParams{

		timeout: timeout,
	}
}

// NewListAPIKeyPrivilegesParamsWithContext creates a new ListAPIKeyPrivilegesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListAPIKeyPrivilegesParamsWithContext(ctx context.Context) *ListAPIKeyPrivilegesParams {
	var ()
	return &ListAPIKeyPrivilegesParams{

		Context: ctx,
	}
}

// NewListAPIKeyPrivilegesParamsWithHTTPClient creates a new ListAPIKeyPrivilegesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListAPIKeyPrivilegesParamsWithHTTPClient(client *http.Client) *ListAPIKeyPrivilegesParams {
	var ()
	return &ListAPIKeyPrivilegesParams{
		HTTPClient: client,
	}
}

/*ListAPIKeyPrivilegesParams contains all the parameters to send to the API endpoint
for the list Api key privileges operation typically these are written to a http.Request
*/
type ListAPIKeyPrivilegesParams struct {

	/*Key
	  key

	*/
	Key string
	/*Limit
	  The maximum count of returned elements

	*/
	Limit *int32
	/*Offset
	  Start with the n-th element

	*/
	Offset *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list Api key privileges params
func (o *ListAPIKeyPrivilegesParams) WithTimeout(timeout time.Duration) *ListAPIKeyPrivilegesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list Api key privileges params
func (o *ListAPIKeyPrivilegesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list Api key privileges params
func (o *ListAPIKeyPrivilegesParams) WithContext(ctx context.Context) *ListAPIKeyPrivilegesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list Api key privileges params
func (o *ListAPIKeyPrivilegesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list Api key privileges params
func (o *ListAPIKeyPrivilegesParams) WithHTTPClient(client *http.Client) *ListAPIKeyPrivilegesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list Api key privileges params
func (o *ListAPIKeyPrivilegesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKey adds the key to the list Api key privileges params
func (o *ListAPIKeyPrivilegesParams) WithKey(key string) *ListAPIKeyPrivilegesParams {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the list Api key privileges params
func (o *ListAPIKeyPrivilegesParams) SetKey(key string) {
	o.Key = key
}

// WithLimit adds the limit to the list Api key privileges params
func (o *ListAPIKeyPrivilegesParams) WithLimit(limit *int32) *ListAPIKeyPrivilegesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list Api key privileges params
func (o *ListAPIKeyPrivilegesParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithOffset adds the offset to the list Api key privileges params
func (o *ListAPIKeyPrivilegesParams) WithOffset(offset *int32) *ListAPIKeyPrivilegesParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the list Api key privileges params
func (o *ListAPIKeyPrivilegesParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *ListAPIKeyPrivilegesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param key
	if err := r.SetPathParam("key", o.Key); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
